### ISSUE TITLE
Support for text plain files (.txt, .map, .bat, etc...)

### ISSUE THREAD

**Issue by Duefectu** [gusmanb/ZXBasicStudio#25]
Support for text plain files (.txt, .map, .bat, etc...)

**Comment by gusmanb** [comment]
Text documents are already supported, right now known extensions are ".txt" and ".md", add a comprehensive list of extensions that should be supported as text files and I will add them :)

**Comment by gusmanb** [comment]
Added more extensions, if others needed add an issue with the requested extension.
