### ISSUE TITLE
colour buttons

### ISSUE THREAD

**Issue by ximokom** [gusmanb/ZXBasicStudio#26]
![colour buttons](https://github.com/gusmanb/ZXBasicStudio/assets/35869376/2c264575-ecaa-40c7-a71d-dc08d8da89f6)

There is an aesthetic detail that I will indicate to you as a draft. The effect or color of the buttons when hovering over them should be inverted. Avoid the flashlight effect in a dark environment, it should be whiter when you hover over it and darker when it is not highlighted.

Hay un detalle estetico que a modo de borrador te indico. El efecto o color de los botones al pasar el raton por encima, deberian estar invertidos. Evita el efecto linterna en un entorno dark, deberia ser mas blanco cuando pasa el cursor por encima y mas oscuro cuando no esta señalado.

**Comment by gusmanb** [comment]
Done
