### ISSUE TITLE
Keyboard map deploys automatically

### ISSUE THREAD

**Issue by EddieTheWild** [gusmanb/ZXBasicStudio#35]
In the emulator area, if you deploy the keyboard map while in the BASIC prompt, then, after hiding it, everytime you push Enter on the BASIC prompt (to enter BASIC commands), the keyboard deplays again automatically.

**Comment by gusmanb** [comment]
Ok, this is because the open/close button still has the focus.
As a workaround you can click on the emulator screen and it should stop happening.

I will remove the "focusable" property of the buton on the next release :)

**Comment by gusmanb** [comment]
Corrected, it will be included in the next release.
