### ISSUE TITLE
En Mac no se puede seleccionar el compilador ZXBC, el ensamblador ZXASM ni el emulador de Next

### ISSUE THREAD

**Issue by Duefectu** [gusmanb/ZXBasicStudio#45]
La ventana de selección de ficheros no permite seleccionar "ZXBC", que se ve que en Mac no lleva extensión.
He empaquetado una versión para un usuario de Mac quitando el ReadOnly del TextBox, y le ha ido bien.
Los valores que ha usado son:
/Users/xxx/Downloads/zxbasic/zxbc
/Users/xx/Downloads/zxbasic/zxbasm

**Comment by gusmanb** [comment]
Donde dice "ZXBASM executable" le haces click y se cambia a "All files" y debería de sacar cualquier tipo de archivo, lo has comprobado?

**Comment by gusmanb** [comment]
Actualizado quitando el filtro. En la siguiente release estará incluído.
